# Generated by Django 5.0.7 on 2024-07-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_alter_experience_category_alter_experience_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
