# Generated by Django 5.0.7 on 2024-07-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="experience_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
